services:
  db:
    image: mysql:8.0
    container_name: dropbox-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dropbox_db
    ports:
      - "3315:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 10

  localstack:
    image: localstack/localstack:latest
    container_name: localstack-container
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    environment:
      EXTRA_CORS_ALLOWED_ORIGINS: "*"
      EXTRA_CORS_ALLOWED_HEADERS: "Content-Type,Authorization,Content-Length"
    volumes:
      - ./data/localstack:/var/lib/localstack

  app:
    build:
      context: .
      network: host
    container_name: dropbox-app
    ports:
      - "3015:3015"
    environment:
      APP_PORT: 3015
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: dropbox_db
      DB_PORT: 3306
      JWT_SECRET: dropboxsecret
      AWS_REGION: us-east-1
      AWS_ACCESS_KEY: test
      AWS_SECRET_KEY: test
      AWS_BUCKET_NAME: dropbox-private-bucket
      AWS_ENDPOINT: http://localstack:4566
      AWS_PUBLIC_ENDPOINT: http://localhost:4566
    depends_on:
      db:
        condition: service_healthy
      localstack:
        condition: service_started
